# Generated by Django 5.1.3 on 2024-12-01 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_alter_server_member"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="member",
            field=models.ManyToManyField(
                related_name="server_member", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
